###########################################################################
path_classifiers:
  test:
    - test
extraction:
  cpp:
    prepare:
      packages:
        - build-essential
        - cmake
        - gcc
        - libffi-dev
        - libgl-dev
        - libpoppler-qt5-dev
        - libqt5svg5-dev
        - libssl-dev
        - pybind11-dev
        - python3-dev
        - qt5-default
        - qt5-qmake
        - qtchooser
        - qtbase5-dev
        - qtbase5-dev-tools
        - qttools5-dev
        - zlib1g-dev
    configure:
      command:
        - cmake --version
        - git clone https://gitlab.com/inkscape/lib2geom.git
        - cd lib2geom; git checkout 37876ed4; cd ..
        - cmake
            -S lib2geom
            -B build-lib2geom
            -GNinja
            -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/install
            -D2GEOM_TESTING=OFF
        - cmake --build build-lib2geom --target install
        - cmake
            -S .
            -B build
            -DBUILD_TRANSLATION=OFF
            -DCMAKE_BUILD_TYPE=Release
            -DCMAKE_INSTALL_PREFIX=$LGTM_WORKSPACE/install
    index:
      build_command:
        - cd build
        - make
  python:
    after_prepare:
      - export PATH=$LGTM_WORKSPACE/tools:$PATH
