#!/usr/bin/env bash

file="$1"
: > "$file"
echo >> "$file" "/**********************************************************"
echo >> "$file" "** Generated by $(basename "$0")"
echo >> "$file" "** at $(date)"
echo >> "$file" "** WARNING! All changes made to this file will be lost!"
echo >> "$file" "***********************************************************/"
echo >> "$file" "static constexpr auto git_describe = \"$(git describe --long)\";"
echo >> "$file" "static constexpr auto git_commit = \"$(git rev-parse HEAD)\";"
