#!/usr/bin/env python3

checks = [
        "auto-unexpected-qstringbuilder",
        "child-event-qobject-cast",
        "connect-3arg-lambda",
        "connect-by-name",
        "connect-non-signal",
        "connect-not-normalized",
        "const-signal-or-slot",
        "container-anti-pattern",
        "detaching-temporary",
        "empty-qstringliteral",
        "foreach",
        "fully-qualified-moc-types",
        "incorrect-emit",
        "install-event-filter",
        "lambda-in-connect",
        "lambda-unique-connection",
        "lowercase-qml-type-name",
        "mutable-container-key",
        # "non-pod-global-static",  # not relevant for applications
        "overloaded-signal",
        "overridden-signal",
        "post-event",
        "qcolor-from-literal",
        "qdatetime-utc",
        "qdeleteall",
        "qenums",
        "qfileinfo-exists",
        "qgetenv",
        "qhash-namespace",
        "qlatin1string-non-ascii",
        "qmap-with-pointer-key",
        "qproperty-without-notify",
        "qstring-arg",
        "qstring-comparison-to-implicit-char",
        "qstring-insensitive-allocation",
        "qstring-left",
        "qstring-ref",
        "qt-macros",
        "range-loop-detach",
        "range-loop-reference",
        "returning-data-from-temporary",
        "rule-of-two-soft",
        "skipped-base-method",
        "strict-iterators",
        "temporary-iterator",
        "unused-non-trivial-variable",
        "use-static-qregularexpression",
        "virtual-signal",
        "writing-to-temporary",
        "wrong-qevent-cast",
        "wrong-qglobalstatic",
]

print(",".join(checks))
